-- Criando a tabela person
CREATE TABLE public.person (
    id BIGINT NOT NULL,
    address CHARACTER VARYING(100) NOT NULL,
    first_name CHARACTER VARYING(50) NOT NULL,
    gender CHARACTER VARYING(6) NOT NULL,
    last_name CHARACTER VARYING(50) NOT NULL
);

-- Configurando sequência da coluna id
ALTER TABLE public.person
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.person_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

-- Adicionando chave primária
ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);
